FROM node:18-alpine3.17

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 3000
RUN chown -R nextjs:nodejs /app


USER nextjs

CMD ["yarn", "dev"]
