version: '3.9'
services:
  dyssomnia-front:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - dyssomnia-network
    deploy:
      replicas: 1

networks:
  dyssomnia-network:
    name: dyssomnia-network
