version: '3.9'
services:
  dyssomnia-front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    networks:
      - dyssomnia-network
    deploy:
      replicas: 1

networks:
  dyssomnia-network:
    name: dyssomnia-network
