name: Deploy Dyssomnia
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/dyssomnia-scanner:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAG }}

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker stop dyssomnia-scanner || true
            docker rm dyssomnia-scanner || true
            docker pull ${{ env.DOCKER_IMAGE_TAG }}
            docker run -d --name dyssomnia-scanner \
              -e NODE_ENV=production \
              -e "DYSSOMNIA_API=${{ secrets.DYSSOMNIA_API }}" \
              -e "APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}" \
              -e "NEXT_PUBLIC_DYSSOMNIA_API=${{ secrets.NEXT_PUBLIC_DYSSOMNIA_API }}" \
              -p 3000:3000 \
              ${{ env.DOCKER_IMAGE_TAG }}
